# Generated by Django 6.1.1 on 2026-09-08 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metal_code', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='limit', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('price_per_gram', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('executed_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('executed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_executions', to='trading.order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_executions', to='trading.order')),
            ],
            options={
                'db_table': 'trading_order_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'created_at'], name='trading_ord_user_id_83441e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['metal_code', 'side', 'status'], name='trading_ord_metal_c_234a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key'], name='trading_ord_idempot_72cd53_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='order_remaining_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_gram__gt', 0)), name='order_price_positive'),
        ),
    ]
