# Generated by Django 6.1.1 on 2026-09-12 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_executions', to='trading.order'),
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='sell_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_executions', to='trading.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'created_at'], name='trading_ord_user_id_83441e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['metal_code', 'side', 'status'], name='trading_ord_metal_c_234a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key'], name='trading_ord_idempot_72cd53_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='order_remaining_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_gram__gt', 0)), name='order_price_positive'),
        ),
    ]
