# Generated by Django 6.1.1 on 2026-09-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreciousMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(default='gram', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_metals',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_gram', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source', models.CharField(default='internal_provider', max_length=80)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.preciousmetal')),
            ],
            options={
                'db_table': 'market_prices',
                'indexes': [models.Index(fields=['metal', 'valid_from'], name='market_pric_metal_i_04f2b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_gram', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='market.preciousmetal')),
            ],
            options={
                'db_table': 'market_price_history',
                'indexes': [models.Index(fields=['metal', 'recorded_at'], name='market_pric_metal_i_f1b6b4_idx')],
            },
        ),
    ]
