# Generated by Django 6.1.1 on 2026-09-08 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=12)),
                ('metal_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
