# Generated by Django 6.1.1 on 2026-09-06 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Optional, international format (e.g. +989121234567).', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in international format, e.g. '+989121234567'.", regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
