# Generated by Django 6.1.1 on 2026-09-15 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, help_text='نام کامل کاربر', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='شماره موبایل به فرمت بین\u200cالمللی (مثال: +989036610574)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست. مثال\u200cهای صحیح: 09036610574 یا +989036610574', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
    ]
