# Generated by Django 6.1.1 on 2026-09-08 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Optional, international format (e.g. +989121234567).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in international format, e.g. '+989121234567'.", regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
