# Generated by Django 6.1.1 on 2026-09-12 17:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metal_code', models.CharField(db_index=True, max_length=20)),
                ('available_quantity', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('locked_quantity', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_holdings',
                'indexes': [models.Index(fields=['user', 'metal_code'], name='asset_holdi_user_id_455f65_idx'), models.Index(fields=['user', 'available_quantity'], name='asset_holdi_user_id_e91a93_idx')],
                'unique_together': {('user', 'metal_code')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
                'indexes': [models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'), models.Index(fields=['-updated_at'], name='wallets_updated_ad4b6f_idx')],
            },
        ),
    ]
