# Generated by Django 6.1.1 on 2026-09-11 12:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='assetholding',
            name='available_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='assetholding',
            name='locked_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='assetholding',
            name='metal_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assetholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddIndex(
            model_name='assetholding',
            index=models.Index(fields=['user', 'metal_code'], name='asset_holdi_user_id_455f65_idx'),
        ),
        migrations.AddIndex(
            model_name='assetholding',
            index=models.Index(fields=['user', 'available_quantity'], name='asset_holdi_user_id_e91a93_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['-updated_at'], name='wallets_updated_ad4b6f_idx'),
        ),
    ]
